#!/bin/bash

wget https://raw.githubusercontent.com/trilitheus/esxi_bash/master/vm_command
docker-compose build
docker-compose up -d
if [[ ${1} == "-debug" ]]; then
  packer build -debug centos7_esxi.json
else
  packer build centos7_esxi.json
fi
docker-compose stop
docker-compose rm -f
